export const API_URL = "http://localhost:8888/frameworkapi/api";

export const MAIN_COD = {
  GATE_IO: "GIO",
  CNTR_STS: "CTS",
  COP_STS: "COPSTS",
  COP_MOD: "COPMOD",
  YON: "YON",
  FOE: "FOE",
};

export const MAIN_COD_ITEM_TYP = {
  MAIN_COD: "MAIN_COD",
  COD_NAME: "COD_NAME",
  COD_DESC: "COD_DESC",
  COD_NAME_DESC: "COD_NAME_DESC",
  MAIN_COD_DESC: "MAIN_COD_DESC",
};

export const GET_MAIN_CODE_OPT = {
  DISPLAY_SEQ: "DISPLAY_SEQ",
  MAIN_COD: "MAIN_COD",
};

export const GENERAL_COD = {
  MASH_GRP: "MASH_GRP",
  BITT: "BITT",
  AGS_BASIC_CATEGORY: "AGS_BASIC_CATEGORY",
  DAMAGE: "DAMAGE",
  BLOCK: "BLOCK",
  BAY: "BAY",
  SERVICE_AREA: "SERVICE_AREA",
  LANE: "LANE",
  BERTH: "BERTH",
  YT: "YT",
  QC: "QC",
  TRUCKER: "TRUCKER",
  VVD: "VVD",
  VVDNEW: "VVDNEW",
  VVDACT: "VVDACT",
  VVDACTALL: "VVDACTALL",
  VVD_LATEST: "VVD_LATEST",
  VESSEL: "VESSEL",
  PORT: "PORT",
  PORT_ONLY: "PORT_ONLY",
  PORT_BY_ROUTE: "PORT_BY_ROUTE",
  PORT_BY_VVD: "PORT_BY_VVD",
  ROUTE: "ROUTE",
  ROUTEGROUP: "ROUTEGROUP",
  NATION: "NATION",
  OPERATOR: "OPERATOR",
  ACT_OPR: "ACT_OPR",
  CNTR_SIZE: "CNTR_SIZE",
  CNTR_TYPE: "CNTR_TYPE",
  CNTR_OPR_TYPE: "CNTR_OPR_TYPE",
  CARGO_TYPE: "CARGO_TYPE",
  ISO_SZTP: "ISO_SZTP",
  LINER_SZTP: "LINER_SZTP",
  CYS_OPR: "CYS_OPR",
  CY_USAGE_COD: "CY_USAGE_COD",
  CURRENCY: "CURRENCY",
  POOL_SCHE_EQP_TYP: "POOL_SCHE_EQP_TYP",
  POOL_SCHE_EQP_NO: "POOL_SCHE_EQP_NO",
  TARIFF_DUE_TYP: "TARIFF_DUE_TYP",
  CNTR_HOLD: "CNTR_HOLD",
  GATE_NO: "GATE_NO",
  VESSEL_BAY: "VESSEL_BAY",
};
